services:
  mysql:
    image: mysql:latest
    container_name: worduel-mysql
    environment:
      MYSQL_DATABASE: worduelDB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data: